### ISSUE TITLE
--enable-libnpp missing for CUDA based image scaling

### ISSUE THREAD

**Issue by paroj** [snapcrafters/ffmpeg#18]
see: https://developer.nvidia.com/ffmpeg

are there reasons for not enabling this?

**Comment by popey** [comment]
Let's see!

**Comment by flexiondotorg** [comment]
I have tried to include this in the past, the issue are:

  * The Cuda SDK is not available from the Ubuntu archive, so requires a 1GB download.
  * The SDK is amd64 only and this ffmpeg supports all architectures.
  * I am uncertain if we can redistribute Cuda libraries.

**Comment by popey** [comment]
I suspect you mean `build-packages` for the `nvidia-cg-dev`, right?
Even so, I tried building locally and it still errors looking for libnpp. Does it also require https://developer.nvidia.com/npp ?

**Comment by paroj** [comment]
could reproduce the problem. The issue is that the Ubuntu cude 7.5 does not provide the nppidei library that ffmpeg checks for.
Out of curiosity I removed the check as

```diff
diff --git a/configure b/configure
index 642c13d..b127549 100755
--- a/configure
+++ b/configure
@@ -6116,7 +6116,7 @@ enabled libmp3lame        && require "libmp3lame >= 3.98.3" lame/lame.h lame_set
 enabled libmysofa         && { check_pkg_config libmysofa libmysofa mysofa.h mysofa_load ||
                                require libmysofa mysofa.h mysofa_load -lmysofa $zlib_extralibs; }
 enabled libnpp            && { check_lib libnpp npp.h nppGetLibVersion -lnppig -lnppicc -lnppc -lnppidei ||
-                               check_lib libnpp npp.h nppGetLibVersion -lnppi -lnppc -lnppidei ||
+                               check_lib libnpp npp.h nppGetLibVersion -lnppi -lnppc ||
                                die "ERROR: libnpp not found"; }
 enabled libopencore_amrnb && require libopencore_amrnb opencore-amrnb/interf_dec.h Decoder_Interface_init -lopencore-amrnb
 enabled libopencore_amrwb && require libopencore_amrwb opencore-amrwb/dec_if.h D_IF_init -lopencore-amrwb
```

and it builds/ runs fine. Tested using the pipeline from the nvidia page:
```
ffmpeg -hwaccel cuvid -c:v h264_cuvid -i <input.mp4> -vf scale_npp=1280:720 -c:v h264_nvenc <output.mp4>
```

**Comment by henry88g** [comment]
A snap build with libnpp support (Ubuntu 18.04 / Nvidia GeForce GTX 1060) would make my world.  I'm so pleased to see you getting there.
