### ISSUE TITLE
ffmpeg snap fails on 17.10

### ISSUE THREAD

**Issue by popey** [snapcrafters/ffmpeg#2]
```
alan@deep-thought:~$ snap run ffmpeg
/snap/ffmpeg/3/usr/local/bin/ffmpeg: error while loading shared libraries: libpulsecommon-8.0.so: cannot open shared object file: No such file or directory
```

```
alan@deep-thought:~$ snap version
snap    2.27.6+17.10
snapd   2.27.6+17.10
series  16
ubuntu  17.10
kernel  4.13.0-12-generic
```

```
alan@deep-thought:~$ snap info ffmpeg
name:      ffmpeg
summary:   "Record, convert, and stream audio and video"
publisher: snapcrafters
description: |
  FFmpeg is a collection of libraries and tools to process multimedia content
  such as audio, video, subtitles and related metadata.
  
snap-id: Ee7LGphwQR669pcfCCdl0oJQouta69to
commands:
  - ffmpeg
tracking:    stable
installed:   N-76538-gb83c849 (3) 150MB classic
refreshed:   2017-08-23 14:44:41 +0100 BST
channels:                         
  stable:    N-76538-gb83c849 (3) 150MB classic
  candidate: ↑                          
  beta:      ↑                          
  edge:      N-76538-gb83c849 (3) 150MB classic
```

**Comment by Ads20000** [comment]
Hmm, any idea what happens if you bump the version of that snap? Are there things depending on this snap? Can we safely update it (maybe using [proper releases](https://git.ffmpeg.org/ffmpeg.git) (see the tags)) rather than particular commits?

**Comment by alexhallam** [comment]
I also just experienced this problem today.
```

snap info ffmpeg
name:      ffmpeg
summary:   Record, convert, and stream audio and video
publisher: snapcrafters
contact:   https://github.com/snapcrafters/ffmpeg/issues
description: |
  FFmpeg is a collection of libraries and tools to process multimedia content
  such as audio, video, subtitles and related metadata.
snap-id: Ee7LGphwQR669pcfCCdl0oJQouta69to
commands:
  - ffmpeg
tracking:    stable
installed:   N-76538-gb83c849 (3) 150MB classic
refreshed:   2017-08-23 09:44:41 -0400 EDT
channels:                         
  stable:    N-76538-gb83c849 (3) 150MB classic
  candidate: ↑                          
  beta:      ↑                          
  edge:      N-76538-gb83c849 (8) 150MB classic

```

**Comment by flynet** [comment]
+1

lexander@Golovko:~$ sudo apt install ffmpeg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ffmpeg : Depends: libavdevice57 (>= 7:3.3.4) but it is not going to be installed
          Depends: libavfilter6 (>= 7:3.3.4) but it is not going to be installed or
                   libavfilter-extra6 (>= 7:3.3.4) but it is not going to be installed


snap ffmpeg is already installed

**Comment by Ads20000** [comment]
`apt` is unrelated to snap.

**Comment by LaHaine** [comment]
I have just installed the snap on Ubuntu 18.04. It still contains this bug, so please release an update.

**Comment by Kiranprajapati2719** [comment]
Hey any update on this issue???

**Comment by Kiranprajapati2719** [comment]
Come on I'm having the same issue here...
/snap/ffmpeg/3/usr/local/bin/ffmpeg: error while loading shared libraries: libpulsecommon-8.0.so: cannot open shared object file: No such file or directory

**Comment by Ads20000** [comment]
Unless you know how to fix the problem and submit a PR you're just going to have to wait until @flexiondotorg or someone has the time to have a look I think :)
