### ISSUE TITLE
Nasm build error

### ISSUE THREAD

**Issue by jonno85uk** [snapcrafters/ffmpeg#24]
cd rdoff && ln -s rdf2bin rdf2ihx
make install DESTDIR=/home/jon/Downloads/ffmpeg/parts/nasm/install
mkdir -p /usr/bin
/usr/bin/install -c nasm /usr/bin/nasm
/usr/bin/install: cannot create regular file '/usr/bin/nasm': Permission denied
Makefile:337: recipe for target 'install' failed
make: *** [install] Error 1
Failed to run 'make install DESTDIR=/home/jon/Downloads/ffmpeg/parts/nasm/install' for 'nasm': Exited with code 2.
Verify that the part is using the correct parameters and try again.

rev c5b0dacae3e12ced9e5cccf084e3e0060e4d4315

**Comment by flexiondotorg** [comment]
I can't reproduce this issue. How are you invoking `snapcraft`?

**Comment by jonno85uk** [comment]
I can no longer reproduce. I just ran snapcraft.

However, after cloning afresh, i get a different build issue.

Ubuntu 18.04 amd64, snapcraft, version 2.43.1+18.4

Close and open another?
