### ISSUE TITLE
add command wrapper for ffprobe

### ISSUE THREAD

**Issue by DeftNerd** [snapcrafters/ffmpeg#3]
The `ffmpeg` snap also includes the useful `ffprobe` utility. 

Can you create a command wrapper and update the snap.yaml file to enable usage of the bundled ffprobe utility?

It would be nice to have it as a symlink in the /snap/bin path along with the `ffmpeg` symlink

**Comment by dandelionred** [comment]
Support. ffmpeg and ffprobe are twins like. Don't separate them please.

**Comment by flexiondotorg** [comment]
Closed via https://github.com/snapcrafters/ffmpeg/commit/c7883eb2778377625b375ebca56c4f71cf082f9b

**Comment by degski** [comment]
@popey Great, that's f'in' quick [the reaction]! When will that 'next update' be available?
