### ISSUE TITLE
ffprobe missing

### ISSUE THREAD

**Issue by NNois** [snapcrafters/ffmpeg#35]
Hi,
FFprobe is missing on the snap package
(FFmpeg 4.1 and edge version)

**Comment by mc4man** [comment]
snap info ffmpeg will show you the commands, i.e,
ffmpeg
ffmpeg.ffplay
ffmpeg.ffprobe

**Comment by Shanghai-Tom** [comment]
really ? 
The ffmpeg snap developer wants me to edit ALL my scripts that invoke ffprobe on batches of files to invoke ffmpeg.ffprobe ?

WHY ????

ffmpeg by itself is fine, but not ffprobe or ffplay ?

I'm sorry to say that if this is the new standard of snaps them I'm done with them !

! Even microsoft isn't this downward compatibility broken !

Until this is resolved I'm uninstalling the snap and reverting to bog-standard non-snap ffmpeg.

**Comment by Shanghai-Tom** [comment]
out of anger, I tried ffmpeg.ffprobe, and it fails as below, it would seem it cannot parse the file name I passed in, 
REAL ffprobe has no such issue

Directory Listing:  ls -al "/LAPTOP/TV_SERIES/Madam Secretary (2014)/Season 06"
-rw-rw-r-- 1 tombot tombot 2059253416 Nov 24 12:00 'Madam Secretary - S06E08 - Ships and Countries.mp4'

ffmpeg.ffprobe "/LAPTOP/TV_SERIES/Madam Secretary (2014)/Season 06/Madam Secretary - S06E08 - Ships and Countries.mp4"

ffprobe version n4.2.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
  configuration: --prefix= --prefix=/usr --disable-debug --disable-doc --disable-static --enable-avisynth --enable-cuda --enable-cuvid --enable-libdrm --enable-ffplay --enable-gnutls --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopus --enable-libpulse --enable-sdl2 --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxvid --enable-nonfree --enable-nvenc --enable-omx --enable-openal --enable-opencl --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100

Gives the error message:

/LAPTOP/TV_SERIES/Madam Secretary (2014)/Season 06/Madam Secretary - S06E08 - Ships and Countries.mp4: No such file or directory

**Comment by Shanghai-Tom** [comment]
Stock ffmpeg .deb reinstalled, all is fine, recalled the command , dropped ffmpeg. from it and it executes without error

 ffprobe "/LAPTOP/TV_SERIES/Madam Secretary (2014)/Season 06/Madam Secretary - S06E08 - Ships and Countries.mp4"
ffprobe version 4.1.4-1build2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/LAPTOP/TV_SERIES/Madam Secretary (2014)/Season 06/Madam Secretary - S06E08 - Ships and Countries.mp4':
  Metadata:
    major_brand     : isom
etc etc etc

**Comment by mc4man** [comment]
@Shanghai-Tom 
snaps have limited access to locations, where your file  above is located  likely isn't supported.
If using 18.04 then I've an ffmpeg build here that progress every month or so.
Read page before deciding if to use..
https://launchpad.net/~mc3man/+archive/ubuntu/bionic-media

**Comment by Shanghai-Tom** [comment]
Hi mc4man,
Thanks for the update, I won't be continuing with this snap ( or any other ) until:

1. It's on current ubuntu, I'm at 19.10 eoan level, the Ubuntu deb's in the repositories are at a level that matches the Ubuntu level, not over 1 year behind, snaps could potentially be 'old' unless the Kernel or other system libraries makes a change that the libraries embedded in the snap cannot function with.

2. It can access all the files I already have access to, btw, where is the dialog to allow snaps access to the same data as the user can access ? or schedule snap updates when suitable ? 

   Data access requirements have to be the same as the user invoking the snap, so much for the much vaunted 'snaps are drop in replacements'

3. ffprobe becomes ffprobe and not ffmpeg.ffprobe, same for ffplay, I point blank refuse to
   update all my scripts, and the scripts on remote NAS devices that SSH into the system to perform video conversions, 

they all use ffprobe to analyse the file before generating dynamic conversion options for ffmpeg.

4. it enables ALL the same compile options as the stock DEB version, check the configuration header lines in my examples above for the two different versions.

5. Snap stops updating applications whenever it feels like it, this is a version control nightmare

and finally

6. Snaps in general MUST follow my desktop settings, such as font, mouse pointer scheme, AND their size

I have a 4k res 27 inch screen, Chromium snap refuses to use my enlarged mouse pointer and as a result it shows on my screen at about 1.2mm, quite often I have to really look for it, so, Chromium snap bites the dust too.

This is my first, and probably last use of snaps for some time until they have matured to the point where they do become drop in replacements.

Why ?

1. I have no control over when it downloads updates - which can break existing functions - and just how many testers validate the snap doesn't regress, or have security malware embedded ?

2. I have NO idea what changes and incompatibilities it may introduce in an update

3. If I'm on a mobile connection and this update kicks in and starts downloading then my link response is toast, and I'm paying for that.

   ( forget the 'auto' link test regarding metered / non-metered, it's as much use as a chocolate percolator jug, especially if you use a vpn on that mobile link for the necessary link security 
The endpoint is then going to be a 'fixed' ip owned by the vpn operator  )

At the moment my system is setup to receive and install Security fixes daily, anything else it advises me, I then read the tech update doc supplied in the update and decide WHEN I can afford to disrupt the system to install that particular update, especially if it requires a reboot.

So... I have STOPped the Snap service
        to make sure it doesn't start on reboot I have also MASKed it

for anyone else, here's the script to turn it on and off at your discretion to receive updates, run with sudo or as admin-root

#!/bin/bash
set -x
systemctl unmask snapd.service
systemctl start snapd.service
systemctl status --no-pager snapd.service
snap refresh
kill -9 $(pgrep snapd)
systemctl stop snapd.service
systemctl mask snapd.service

( I'm assuming that with this script that you simply don't care what software updates have been applied to applications that may be critical to you )

Regards,
Tom.

**Comment by pav5000** [comment]
> really ?
> The ffmpeg snap developer wants me to edit ALL my scripts that invoke ffprobe on batches of files to invoke ffmpeg.ffprobe ?
> 
> WHY ????
> 
> ffmpeg by itself is fine, but not ffprobe or ffplay ?
> 
> I'm sorry to say that if this is the new standard of snaps them I'm done with them !
> 
> ! Even microsoft isn't this downward compatibility broken !
> 
> Until this is resolved I'm uninstalling the snap and reverting to bog-standard non-snap ffmpeg.

I solved it this way:
$ snap alias ffmpeg.ffprobe ffprobe

Now ffprobe works as expected.

**Comment by Shanghai-Tom** [comment]
Thanks Alexandr, the problem still remains that it can't see the files, whatever restrictions are built-in to snaps on storage access means that for some reason they can't see all the files that I can see.

Standard ffmpeg deb package can see them, just not the snap.

I'm not rearranging my file structure or permissions just to suit a snap, so until they are fully compatible they can never be considered a 'drop in replacement'.

Best regards,
Tom.

Feb 14, 2020 11:50:00 AM Alexandr Pavlyuk <notifications@github.com>:

**Comment by galstudio** [comment]
sudo snap connect ffmpeg:removable-media
