### ISSUE TITLE
"No such file or directory", even though it exists

### ISSUE THREAD

**Issue by DoubyCz** [snapcrafters/ffmpeg#41]
**ffmpeg -i input.mp4 output.mkv**
_awlays results in error "input.mp4: No such file or directory" or "Permission denied"_

I am pretty sure ./input.mp4 file exists in working directory (pwd), but why ffmpeg can't see it ? There is no symlink in the way, read/write rights available for user/group/others for all folders in the way and input file too. So where is problem? Btw, ffmpeg installed using "sudo apt install ffmpeg" can see input.mp4, so it is snap package specific problem.

Thank you for your help or any advice.
![access denied to all files ffmpeg](https://user-images.githubusercontent.com/41196960/65431009-15a20880-de19-11e9-8fbc-5c679fe3841d.png)

**Comment by DoubyCz** [comment]
only way how it works is using in/out pipes **cat xx.mkv | ffmpeg -i pipe: -f matroska - > xxx.mkv** ... it workaround (no need to filesystem access at all). But good temporary solution to this problem.

**Comment by DoubyCz** [comment]
And there is snother working sollution, install this package using --devmode
**sudo snap install ffmpeg --devmode**

Then it works without **"can't access any file"** problem.

**Comment by DoubyCz** [comment]
And last found sollution it easiest solution.

There is no need to use --devmode or in/out pipes. Just open your graphical Software Center and find your FFMPEG app installed from SNAP repository.

There you can find PERMISSIONS button, click on it, and enable "Read/write files on removable storage devices" permission. Then it works and you can read/write files in your own home directory.

This is bug, imo. Home directory is not "removable device" :-) But it works ...

**Comment by flexiondotorg** [comment]
The `home` interface, which is connected automatically, provides access to your hojme directory. The `removable-media` interface, which is not connected by default, is what provides access to removable storage such as USB sticks and SD cards.

**Comment by evadne** [comment]
Snap infrastructure does not allow access to files in arbitrary locations, devmode would not work for example if you have a ZFS pool in a nonstandard location (based on Ubuntu 22.04)

Your best option is to change where the filesystem is mounted, alternatively set up a bind mount so you have it in /media/$user to placate the Snap
