### ISSUE TITLE
Snapstore states ffmpeg snap is licensed under LGPLv2.1+ when it is built in GPLv3 mode

### ISSUE THREAD

**Issue by ahayzen** [snapcrafters/ffmpeg#47]
The snapstore https://snapcraft.io/ffmpeg states "License LGPL-2.1+", but the snap is built with `--enable-gpl` [0] and `--enable-verison3` [1] which makes this package GPLv3.

0 - https://github.com/snapcrafters/ffmpeg/blob/9bbd6fd2a975cac62622783367f81b33365b4ea4/snap/snapcraft.yaml#L145
1 - https://github.com/snapcrafters/ffmpeg/blob/9bbd6fd2a975cac62622783367f81b33365b4ea4/snap/snapcraft.yaml#L175

**Comment by flexiondotorg** [comment]
I've corrected the Snap Store listing.
