### ISSUE TITLE
./ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Holston5** [snapcrafters/ffmpeg#5]
Getting the aforementioned error when trying to run the snap with this command:

/snap/ffmpeg/206/usr/bin$ ./ffmpeg -vaapi_device /dev/dri/renderD128 -i ~/test.mp4 -vf 'format=nv12,hwupload' -c:v h264_amf ~/output.mp4

The file exists in ../lib/

Using:

LD_PRELOAD=/snap/ffmpeg/206/usr/lib/libavdevice.so.58 ./ffmpeg -vaapi_device /dev/dri/renderD128 -i ~/Videos/test.mp4 -vf 'format=nv12,hwupload' -c:v h264_amf ~/output.mp4

Seems to correctly load the lib, as it instead complains:

./ffmpeg: error while loading shared libraries: libavfilter.so.7: cannot open shared object file: No such file or directory

so loading the library path:

LD_LIBRARY_PATH=/snap/ffmpeg/206/usr/lib/ ./ffmpeg -vaapi_device /dev/dri/renderD128 -i ~/Videos/test.mp4 -vf 'format=nv12,hwupload' -c:v h264_amf ~/output.mp4

./ffmpeg: error while loading shared libraries: libcrystalhd.so.3: cannot open shared object file: No such file or directory

**Comment by jose-oc** [comment]
I have the same error. It was working fine so I suppose the latest update has broken something.

I'm going to add some information:

*Snap version*
```
$ snap version
snap    2.35
snapd   2.35
series  16
ubuntu  18.04
kernel  4.15.0-34-generic
```

*ffmpeg version*
```
$ snap info ffmpeg
name:      ffmpeg
summary:   A complete solution to record, convert and stream audio and video.
publisher: Snapcrafters
contact:   https://github.com/snapcrafters/ffmpeg/issues
license:   unset
description: |
  FFmpeg is the leading multimedia framework, able to decode, encode, transcode, mux, demux, stream,
  filter and play pretty much anything that humans and machines have created. It supports the most
  obscure ancient formats up to the cutting edge. No matter if they were designed by some standards
  committee, the community or a corporation.
commands:
  - ffmpeg
snap-id:      Ee7LGphwQR669pcfCCdl0oJQouta69to
tracking:     stable
refresh-date: today at 14:31 CEST
channels:                     
  stable:    4.0.2 (206) 46MB -
  candidate: ↑                
  beta:      ↑                
  edge:      4.0.2 (250) 45MB -
installed:   4.0.2 (206) 46MB -
```

*ffmpeg error*
```
$ ffmpeg
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error:  GLXBadContext
  Request Major code 155 (GLX)
  Request Minor code 6 ()
  Error Serial #55
  Current Serial #54
ffmpeg version n4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix= --prefix=/usr --disable-debug --disable-doc --disable-static --enable-avisynth --enable-cuda --enable-cuvid --enable-libdrm --enable-gpl --enable-libass --enable-libfdk-aac --enable-libfontconfig --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libv4l2 --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libxcb --enable-nonfree --enable-nvenc --enable-omx --enable-runtime-cpudetect --enable-shared --enable-vaapi --enable-vdpau --enable-version3 --enable-xlib
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
```

*ffprobe error*
```
$ /snap/ffmpeg/current/usr/bin/ffprobe
/snap/ffmpeg/current/usr/bin/ffprobe: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory
```

However those dependencies exist:
```
$ find /snap/ffmpeg -name libavdevice.so.58
/snap/ffmpeg/206/usr/lib/libavdevice.so.58

$ find /snap/ffmpeg -name i965_dri.so
/snap/ffmpeg/206/usr/lib/x86_64-linux-gnu/dri/i965_dri.so

$ find /snap/ffmpeg -name swrast_dri.so
/snap/ffmpeg/206/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
```

**Comment by Holston5** [comment]
Yes, you can force them all through like this though and it works:

LD_LIBRARY_PATH=/snap/ffmpeg/206/usr/lib/:/snap/ffmpeg/206/usr/lib/x86_64-linux-gnu:/snap/ffmpeg/206/usr/lib/dri:/snap/ffmpeg/206/lib/x86_64-linux-gnu/ ./ffmpeg <rest of ffmpeg command>

**Comment by jose-oc** [comment]
Yes, that works, but the full path to ffmpeg has to be provided:
`LD_LIBRARY_PATH=/snap/ffmpeg/206/usr/lib/:/snap/ffmpeg/206/usr/lib/x86_64-linux-gnu:/snap/ffmpeg/206/usr/lib/dri:/snap/ffmpeg/206/lib/x86_64-linux-gnu/ /snap/ffmpeg/current/usr/bin/ffmpeg`

Thanks.

**Comment by flexiondotorg** [comment]
If you use `snap run ffmpeg` or `/snap/bin/ffmpeg` then there is no need to provide `LD_LIBRARY_PATH`. By executing ffmpeg directly from the `/snap/ffmpeg` you are sidestepping the wrappers that automatically setup the environment for you. Don't do that :smile:

**Comment by jose-oc** [comment]
@flexiondotorg I'm afraid that didn't work for me, I got the same `unable to load driver` errors using both `snap run ffmpeg` and `/snap/bin/ffmpeg`.

**Comment by Holston5** [comment]
Same here.
