### ISSUE TITLE
snap version cannot pick up files in current directory

### ISSUE THREAD

**Issue by ginobean** [snapcrafters/ffmpeg#61]
This seems pretty basic, but the snap version of ffmpeg, when I tried it about a week ago, was not able to pick up the name of a video file that was already in the current directory.

This is part of a shell script that I am using:

`if ! ffmpeg -y -loglevel panic -i "${infile}" -map_metadata -1 -vcodec copy -acodec copy "${outfile}" < /dev/null
`

When ${infile} is an mp4 video file in the current directory, the snap version of ffmpeg was not able to detect it. 

Mystified, as a test, I uninstalled the snap version of ffmpeg, used 'sudo apt install ffmpeg' to install the standard ffmpeg version and the aforementioned script worked fine.

**Comment by flexiondotorg** [comment]
The FFmpeg snap is confined. It can only access files in your home directory, removable media or optical media.

In order to access data on removable media or optical media to appropriate interfaces will need connecting:

```
snap connect ffmpeg:removable-media
snap connect ffmpeg:optical-drive
```

**Comment by ginobean** [comment]
Unfortunately, what end users see is that it simply doesn't to work. Is there some way to have the snap version of ffmpeg either put up a disclaimer advising them to use the 'apt' version or at least give the user the option of enabling the aforementioned options via a gui interface?
