### ISSUE TITLE
[Enhancement]: Enable Intel quick sync hardware acceleration feature

### ISSUE THREAD

**Issue by hurelhuyag** [snapcrafters/ffmpeg#74]
### What changes would you like?

Enable Intel quick sync hardware acceleration feature. This is way better than software codecs.

### Any extra information?

I hope this will be enabled with those parameters.
`--enable-nonfree --enable-libmfx`

**Comment by brlin-tw** [comment]
> `--enable-nonfree`

This is a no-no as it enables non-free component that makes the resulting snap not legally redistributable.  I'm afraid such a configuration is not possible aside from the users building the snaps themselves.

**Comment by brlin-tw** [comment]
Thanks for your input, however, I'm going to close this issue due to the above reasoning, do reply if I'm wrong otherwise.

**Comment by hurelhuyag** [comment]
@brlin-tw Actual non-free stuff is installed independently. Isn't it? Currently, Intel's non-free binaries working with VAAPI. Just like that. 
Btw, `--enable-nonfree` maybe not be mandatory, I think.
