### ISSUE TITLE
Issue submitted via apport

### ISSUE THREAD

**Issue by Slavomir9** [snapcrafters/ffmpeg#79]
**ProblemType**
Bug

**Date**
Mon Jul  3 13:34:25 2023

**CurrentDesktop**
ubuntu:GNOME

**ProcEnviron**
LANG=sk_SK.UTF-8
PATH=(custom, no user)
SHELL=/bin/bash
XDG_RUNTIME_DIR=<set>

**DistroRelease**
Ubuntu 23.04

**Uname**
Linux 6.2.0-24-generic x86_64

**Architecture**
amd64

**SnapChanges**
no changes found

**SnapConnections**
Interface         Plug                     Slot               Notes
alsa              ffmpeg:alsa              :alsa              manual
audio-playback    ffmpeg:audio-playback    :audio-playback    -
audio-record      ffmpeg:audio-record      -                  -
camera            ffmpeg:camera            -                  -
desktop           ffmpeg:desktop           :desktop           -
hardware-observe  ffmpeg:hardware-observe  :hardware-observe  manual
home              ffmpeg:home              :home              -
network           ffmpeg:network           :network           -
network-bind      ffmpeg:network-bind      :network-bind      -
opengl            ffmpeg:opengl            :opengl            -
optical-drive     ffmpeg:optical-drive     :optical-drive     -
pulseaudio        ffmpeg:pulseaudio        :pulseaudio        -
removable-media   ffmpeg:removable-media   -                  -
wayland           ffmpeg:wayland           :wayland           -
x11               ffmpeg:x11               :x11               -

**SnapInfo.ffmpeg**
name:      ffmpeg
summary:   A complete solution to record, convert and stream audio and video.
publisher: Snapcrafters*
store-url: https://snapcraft.io/ffmpeg
contact:   https://github.com/snapcrafters/ffmpeg/issues
license:   unset
description: |
  FFmpeg is the leading multimedia framework, able to decode, encode,
  transcode, mux, demux, stream, filter and play pretty much anything that
  humans and machines have created. It supports the most obscure ancient
  formats up to the cutting edge. No matter if they were designed by some
  standards committee, the community or a corporation.
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
commands:
  - ffmpeg.eglinfo
  - ffmpeg
  - ffmpeg.ffplay
  - ffmpeg.ffprobe
  - ffmpeg.glxinfo
  - ffmpeg.srt-ffplay
  - ffmpeg.srt-file-transmit
  - ffmpeg.srt-live-transmit
  - ffmpeg.srt-tunnel
  - ffmpeg.vainfo
  - ffmpeg.vdpauinfo
snap-id:      Ee7LGphwQR669pcfCCdl0oJQouta69to
tracking:     latest/edge
refresh-date: 2023-06-20T19:23:02+02:00
channels:
  latest/stable:    4.3.1                2020-11-08T13:44:35Z (1286)  83MB -
  latest/candidate: ^                                                      
  latest/beta:      ^                                                      
  latest/edge:      n4.4.4-6-gd5fa6e3a91 2023-06-05T06:39:01Z (1357) 161MB -
installed:          n4.4.4-6-gd5fa6e3a91                      (1357) 161MB -

**SnapInfo.core20**
name:      core20
summary:   Runtime environment based on Ubuntu 20.04
publisher: Canonical**
store-url: https://snapcraft.io/core20
contact:   https://github.com/snapcore/core20/issues
license:   unset
description: |
  The base snap based on the Ubuntu 20.04 release.
type:         base
snap-id:      DLqre5XGLbDqg9jPtiAhRRjDuPVa5X1q
tracking:     latest/stable
refresh-date: 2023-07-03T11:57:11+02:00
channels:
  latest/stable:    20230613 2023-06-21T06:10:05Z (1950) 66MB -
  latest/candidate: 20230622 2023-06-28T18:05:29Z (1974) 66MB -
  latest/beta:      20230622 2023-06-26T00:05:57Z (1974) 66MB -
  latest/edge:      20230622 2023-06-23T15:04:52Z (1974) 66MB -
installed:          20230622                      (1974) 66MB base

**SnapGitOwner**
snapcrafters

**SnapGitName**
ffmpeg

**CrashDB**
snap-github

**Package**
ffmpeg 7:5.1.2-3ubuntu1

**SourcePackage**
ffmpeg

**Dependencies**
adduser 3.129ubuntu1
alsa-topology-conf 1.2.5.1-2
alsa-ucm-conf 1.2.6.3-1ubuntu9
apt 2.6.0
apt-utils 2.6.0
base-passwd 3.6.1
ca-certificates 20230311ubuntu0.23.04.1
dbus 1.14.4-1ubuntu1
dbus-bin 1.14.4-1ubuntu1
dbus-daemon 1.14.4-1ubuntu1
dbus-session-bus-common 1.14.4-1ubuntu1
dbus-system-bus-common 1.14.4-1ubuntu1
debconf 1.5.82
debconf-i18n 1.5.82
dpkg 1.21.21ubuntu1
fontconfig 2.14.1-3ubuntu3
fontconfig-config 2.14.1-3ubuntu3
fonts-dejavu-core 2.37-6
gcc-13-base 13-20230320-1ubuntu1
gpgv 2.2.40-1.1ubuntu1
i965-va-driver 2.4.1+dfsg1-1
intel-media-va-driver 23.1.2+dfsg1-1
krb5-locales 1.20.1-1build1
libaacs0 0.11.1-2
libacl1 2.3.1-3
libaom3 3.6.0-1
libapparmor1 3.0.8-1ubuntu2
libapt-pkg6.0 2.6.0
libasound2 1.2.8-1build1
libasound2-data 1.2.8-1build1
libass9 1:0.17.0-2
libasyncns0 0.8-6build2
libaudit-common 1:3.0.9-1
libaudit1 1:3.0.9-1
libavc1394-0 0.5.4-5build2
libavcodec59 7:5.1.2-3ubuntu1
libavdevice59 7:5.1.2-3ubuntu1
libavfilter8 7:5.1.2-3ubuntu1
libavformat59 7:5.1.2-3ubuntu1
libavutil57 7:5.1.2-3ubuntu1
libbdplus0 0.2.0-3
libblas3 3.11.0-2
libblkid1 2.38.1-4ubuntu1
libbluray2 1:1.3.4-1
libbrotli1 1.0.9-2build8
libbs2b0 3.1.0+dfsg-7
libbsd0 0.11.7-4
libbz2-1.0 1.0.8-5build1
libc6 2.37-0ubuntu2
libcaca0 0.99.beta20-3build1
libcairo-gobject2 1.16.0-7
libcairo2 1.16.0-7
libcap-ng0 0.8.3-1build2
libcap2 1:2.66-3ubuntu2.1
libcdio-cdda2 10.2+2.0.1-1
libcdio-paranoia2 10.2+2.0.1-1
libcdio19 2.1.0-4
libchromaprint1 1.5.1-2build1
libcjson1 1.7.15-1
libcodec2-1.0 1.0.5-1ubuntu2
libcom-err2 1.47.0-1ubuntu1
libcrypt1 1:4.4.33-2
libdatrie1 0.2.13-2
libdav1d6 1.0.0-2
libdb5.3 5.3.28+dfsg2-1
libdbus-1-3 1.14.4-1ubuntu1
libdc1394-25 2.2.6-4
libdebconfclient0 0.267ubuntu1
libdecor-0-0 0.1.1-2
libdecor-0-plugin-1-cairo 0.1.1-2
libdeflate0 1.15-1
libdrm-amdgpu1 2.4.114-1
libdrm-common 2.4.114-1
libdrm-intel1 2.4.114-1
libdrm-nouveau2 2.4.114-1
libdrm-radeon1 2.4.114-1
libdrm2 2.4.114-1
libedit2 3.1-20221030-2
libelf1 0.188-2.1
libepoxy0 1.5.10-1
libexpat1 2.5.0-1
libffi8 3.4.4-1
libflac12 1.4.2+ds-2ubuntu1
libflite1 2.2-5
libfontconfig1 2.14.1-3ubuntu3
libfreetype6 2.12.1+dfsg-4ubuntu0.1
libfribidi0 1.0.8-2.1ubuntu1
libgbm1 23.0.2-1ubuntu1
libgcc-s1 13-20230320-1ubuntu1
libgcrypt20 1.10.1-3ubuntu1
libgdk-pixbuf-2.0-0 2.42.10+dfsg-1build1
libgdk-pixbuf2.0-bin 2.42.10+dfsg-1build1
libgdk-pixbuf2.0-common 2.42.10+dfsg-1build1
libgfortran5 13-20230320-1ubuntu1
libgl1 1.6.0-1
libgl1-amber-dri 21.3.9-0ubuntu1
libgl1-mesa-dri 23.0.2-1ubuntu1
libglapi-mesa 23.0.2-1ubuntu1
libglib2.0-0 2.76.1-1
libglib2.0-data 2.76.1-1
libglvnd0 1.6.0-1
libglx-mesa0 23.0.2-1ubuntu1
libglx0 1.6.0-1
libgme0 0.6.3-6
libgmp10 2:6.2.1+dfsg1-1.1ubuntu1
libgnutls30 3.7.8-5ubuntu1
libgomp1 13-20230320-1ubuntu1
libgpg-error-l10n 1.46-1
libgpg-error0 1.46-1
libgpm2 1.20.7-10build1
libgraphite2-3 1.3.14-1build2
libgsm1 1.0.22-1
libgssapi-krb5-2 1.20.1-1build1
libharfbuzz0b 6.0.0+dfsg-3build1
libhogweed6 3.8.1-2
libhwy1 1.0.3-2
libicu72 72.1-3ubuntu2
libidn2-0 2.3.3-1build1
libiec61883-0 1.2.0-6
libigdgmm12 22.3.4+ds1-1
libjack-jackd2-0 1.9.21~dfsg-2
libjbig0 2.1-6ubuntu1
libjpeg-turbo8 2.1.5-2ubuntu1
libjpeg8 8c-2ubuntu11
libjxl0.7 0.7.0-10ubuntu2
libk5crypto3 1.20.1-1build1
libkeyutils1 1.6.3-2
libkrb5-3 1.20.1-1build1
libkrb5support0 1.20.1-1build1
liblapack3 3.11.0-2
liblcms2-2 2.14-2
liblerc4 4.0.0+ds-2ubuntu2
liblilv-0-0 0.24.14-1
libllvm15 1:15.0.7-3
liblocale-gettext-perl 1.07-5
liblz4-1 1.9.4-1
liblzma5 5.4.1-0.2
libmbedcrypto7 2.28.2-1
libmd0 1.0.4-2
libmfx1 22.5.4-1
libmount1 2.38.1-4ubuntu1
libmp3lame0 3.100-6
libmpg123-0 1.31.2-1
libmysofa1 1.3.1~dfsg0-1
libncursesw6 6.4-2ubuntu0.1
libnettle8 3.8.1-2
libnorm1 1.5.9+dfsg-2
libnsl2 1.3.0-2build2
libnss-nis 3.1-0ubuntu6
libnss-nisplus 1.3-0ubuntu6
libnuma1 2.0.16-1
libogg0 1.3.5-3
libopenal-data 1:1.19.1-2build3
libopenal1 1:1.19.1-2build3
libopenjp2-7 2.5.0-1build1
libopenmpt0 0.6.9-1
libopus0 1.3.1-3
libp11-kit0 0.24.1-2ubuntu1
libpam-modules 1.5.2-5ubuntu1
libpam-modules-bin 1.5.2-5ubuntu1
libpam0g 1.5.2-5ubuntu1
libpango-1.0-0 1.50.12+ds-1
libpangocairo-1.0-0 1.50.12+ds-1
libpangoft2-1.0-0 1.50.12+ds-1
libpciaccess0 0.17-2
libpcre2-8-0 10.42-1
libpgm-5.3-0 5.3.128~dfsg-2
libpixman-1-0 0.42.2-1
libplacebo208 4.208.0-3
libpng16-16 1.6.39-2
libpocketsphinx3 0.8.0+real5prealpha+1-15ubuntu1
libpostproc56 7:5.1.2-3ubuntu1
libpulse0 1:16.1+dfsg1-2ubuntu3
librabbitmq4 0.11.0-1
librav1e0 0.5.1-6ubuntu1
libraw1394-11 2.1.2-2build2
librist4 0.2.7+dfsg-1
librsvg2-2 2.54.5+dfsg-1ubuntu2
librsvg2-common 2.54.5+dfsg-1ubuntu2
librubberband2 3.1.2+dfsg0-1
libsamplerate0 0.2.2-3
libsdl2-2.0-0 2.26.3+dfsg-1
libseccomp2 2.5.4-1ubuntu3
libselinux1 3.4-1build4
libsemanage-common 3.4-1build4
libsemanage2 3.4-1build4
libsensors-config 1:3.6.0-7ubuntu1
libsensors5 1:3.6.0-7ubuntu1
libsepol2 3.4-2
libserd-0-0 0.30.16-1
libshine3 3.1.1-2
libslang2 2.3.3-2
libsnappy1v5 1.1.9-3
libsndfile1 1.2.0-1
libsndio7.0 1.9.0-0.3
libsodium23 1.0.18-1build2
libsord-0-0 0.16.14+git221008-1
libsoxr0 0.1.3-4build2
libspeex1 1.2.1-2ubuntu1
libsphinxbase3 0.8+5prealpha+1-16
libsratom-0-0 0.6.14-1
libsrt1.5-gnutls 1.5.1-1
libssh-gcrypt-4 0.10.4-2ubuntu0.1
libssl3 3.0.8-1ubuntu1.2
libstdc++6 13-20230320-1ubuntu1
libsvtav1enc1 1.4.1+dfsg-1
libswresample4 7:5.1.2-3ubuntu1
libswscale6 7:5.1.2-3ubuntu1
libsystemd0 252.5-2ubuntu3
libtasn1-6 4.19.0-2
libtext-charwidth-perl 0.04-11
libtext-iconv-perl 1.7-8
libtext-wrapi18n-perl 0.06-10
libthai-data 0.1.29-1build1
libthai0 0.1.29-1build1
libtheora0 1.1.1+dfsg.1-16.1
libtiff6 4.5.0-5ubuntu1
libtinfo6 6.4-2ubuntu0.1
libtirpc-common 1.3.3+ds-1
libtirpc3 1.3.3+ds-1
libtwolame0 0.4.0-2build2
libudev1 252.5-2ubuntu3
libudfread0 1.1.2-1
libunistring2 1.0-2
libusb-1.0-0 2:1.0.26-1
libva-drm2 2.17.0-1
libva-x11-2 2.17.0-1
libva2 2.17.0-1
libvdpau1 1.5-2
libvidstab1.1 1.1.0-2
libvorbis0a 1.3.7-1build2
libvorbisenc2 1.3.7-1build2
libvorbisfile3 1.3.7-1build2
libvpx7 1.12.0-1ubuntu1
libvulkan1 1.3.239.0-1
libwayland-client0 1.21.0-1
libwayland-cursor0 1.21.0-1
libwayland-egl1 1.21.0-1
libwayland-server0 1.21.0-1
libwebp7 1.2.4-0.1ubuntu0.23.04.1
libwebpmux3 1.2.4-0.1ubuntu0.23.04.1
libx11-6 2:1.8.4-2ubuntu0.2
libx11-data 2:1.8.4-2ubuntu0.2
libx11-xcb1 2:1.8.4-2ubuntu0.2
libx264-164 2:0.164.3095+gitbaee400-2build1
libx265-199 3.5-2
libxau6 1:1.0.9-1build5
libxcb-dri2-0 1.15-1
libxcb-dri3-0 1.15-1
libxcb-glx0 1.15-1
libxcb-present0 1.15-1
libxcb-randr0 1.15-1
libxcb-render0 1.15-1
libxcb-shape0 1.15-1
libxcb-shm0 1.15-1
libxcb-sync1 1.15-1
libxcb-xfixes0 1.15-1
libxcb1 1.15-1
libxcursor1 1:1.2.1-1
libxdmcp6 1:1.1.3-0ubuntu5
libxext6 2:1.3.4-1build1
libxfixes3 1:6.0.0-2
libxi6 2:1.8-1build1
libxkbcommon0 1.5.0-1
libxml2 2.9.14+dfsg-1.1ubuntu0.1
libxrandr2 2:1.5.2-2
libxrender1 1:0.9.10-1.1
libxshmfence1 1.3-1build4
libxss1 1:1.2.3-1build2
libxv1 2:1.0.11-1.1
libxvidcore4 2:1.3.7-1
libxxf86vm1 1:1.1.4-1build3
libxxhash0 0.8.1-1
libzimg2 3.0.4+ds1-1
libzmq5 4.3.4-6
libzstd1 1.5.4+dfsg2-4
libzvbi-common 0.2.41-1
libzvbi0 0.2.41-1
mesa-va-drivers 23.0.2-1ubuntu1
mesa-vdpau-drivers 23.0.2-1ubuntu1
mesa-vulkan-drivers 23.0.2-1ubuntu1
ocl-icd-libopencl1 2.3.1-1
openssl 3.0.8-1ubuntu1.2
passwd 1:4.13+dfsg1-1ubuntu1
perl-base 5.36.0-7ubuntu0.23.04.1
pocketsphinx-en-us 0.8.0+real5prealpha+1-15ubuntu1
sensible-utils 0.0.17+nmu1
shared-mime-info 2.2-1
tar 1.34+dfsg-1.2ubuntu0.1
ubuntu-keyring 2021.03.26
va-driver-all 2.17.0-1
vdpau-driver-all 1.5-2
x11-common 1:7.7+23ubuntu2
xdg-user-dirs 0.18-1
xkb-data 2.38-0ubuntu1
zlib1g 1:1.2.13.dfsg-1ubuntu4

**InstallationMedia**
Ubuntu 23.04 "Lunar Lobster" - Release amd64 (20230418)

**Tags**
 lunar

**InstallationDate**
Installed on 2023-06-19 (14 days ago)

**UpgradeStatus**
No upgrade log present (probably fresh install)

**ProcVersionSignature**
Ubuntu 6.2.0-24.24-generic 6.2.12

**ProcCpuinfoMinimal**
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz
stepping	: 5
microcode	: 0x7
cpu MHz		: 2792.976
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 2
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt aes lahf_lm pti ssbd ibrs ibpb stibp dtherm ida arat flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit mmio_unknown
bogomips	: 5053.95
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

**ApportVersion**
2.26.1-0ubuntu2

**CasperMD5CheckResult**
pass

**Comment by popey** [comment]
There's nothing in this bug report which is actionable. If you have a specific issue which causes the crash in ffmpeg, please provide it in a new issue.
