### ISSUE TITLE
[Enhancement]: connect personal-files plug

### ISSUE THREAD

**Issue by makeitcount** [snapcrafters/ffmpeg#80]
### What changes would you like?

Currently this ffmpeg cannot access files in the hidden folder. To fix that, I tried connecting it manually via

```
sudo snap connect ffmpeg:personal-files
```
But I received this error
> error: snap "ffmpeg" has no plug named "personal-files"

I cannot use ffmpeg without this. Appreciate if this  plug gets added (or there's a workaround to get this access) 

### Any extra information?

ffmpeg v4.3.1

**Comment by popey** [comment]
This is by design. Applications published in the snap store can typically access whatever they need in the home folder, but are prevented from accessing hidden files, such as your ssh keys or gpg keys.

**Comment by makeitcount** [comment]
In that case, what is the workaround? We use ffmpeg script to process temporary files which are situated in a hidden folder. And it is beyond our script's scope to switch folder from hidden to non-hidden folder.
